name: trmsta
version: 0.1.2
description: TRM station info parsing
author: "Michał Krzysztof Feiler <archiet@platinum.edu.pl>"
homepage: "https://github.com/ArchieT/trmsta"
dependencies:
        http: ">=0.11.3 <0.12.0"
